apiVersion: v1

items:
  
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: db
      name: db
    spec:
      ports:
        - name: "3306"
          port: 3306
          targetPort: 3306
      selector:
        io.kompose.service: db
    status:
      loadBalancer: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: homekit
      name: homekit
    spec:
      ports:
        - name: "51826"
          port: 51826
          targetPort: 51826
        - name: "5353"
          port: 5353
          targetPort: 5353
      selector:
        io.kompose.service: homekit
    status:
      loadBalancer: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: mqttautodomo
      name: mqttautodomo
    spec:
      ports:
        - name: "1883"
          port: 1883
          targetPort: 1883
        - name: "9001"
          port: 9001
          targetPort: 9001
      selector:
        io.kompose.service: mqttautodomo
      type: LoadBalancer
    status:
      loadBalancer: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: nodediverso
      name: nodediverso
    spec:
      ports:
        - name: "8085"
          port: 8085
          targetPort: 8085
        - name: "4555"
          port: 4555
          targetPort: 4555
      selector:
        io.kompose.service: nodediverso
    status:
      loadBalancer: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: noderedautodomo
      name: noderedautodomo
    spec:
      ports:
        - name: "1880"
          port: 1880
          targetPort: 1880
        - name: "8082"
          port: 8082
          targetPort: 8082
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: noderedautodomo
      type: LoadBalancer
    status:
      loadBalancer: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: phpmyadmin
      name: phpmyadmin
    spec:
      ports:
        - name: "8081"
          port: 8081
          targetPort: 80
      selector:
        io.kompose.service: phpmyadmin
      type: LoadBalancer
    status:
      loadBalancer: {}
  
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        io.kompose.service: supervisorio
      name: supervisorio
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
        - name: "443"
          port: 443
          targetPort: 443
      selector:
        io.kompose.service: supervisorio
      type: LoadBalancer
    status:
      loadBalancer: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: db
      name: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: db
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: db
        spec:
          containers:
            - env:
                - name: MYSQL_DATABASE
                  value: autohome
                - name: MYSQL_PASSWORD
                  value: UserautohomeMysql1.0bi
                - name: MYSQL_ROOT_PASSWORD
                  value: comida05autocasa1979
                - name: MYSQL_USER
                  value: userautohome
              image: biarms/mysql
              name: db
              ports:
                - containerPort: 3306
              resources: {}
              volumeMounts:
                - mountPath: /docker-entrypoint-initdb.d
                  name: db-hostpath0
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/Lais/mariadb
              name: db-hostpath0
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: homegbridge
      name: homegbridge
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: homegbridge
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: homegbridge
        spec:
          containers:
            - image: eltonssilva/gbridgeconnect:armv7_1.1
              name: homegbridge
              resources: {}
          restartPolicy: Always
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: homekit
      name: homekit
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: homekit
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: homekit
        spec:
          containers:
            - image: eltonssilva/homekit:armv7_1.0
              name: homekit
              ports:
                - containerPort: 51826
                - containerPort: 5353
              resources: {}
              volumeMounts:
                - mountPath: /home/HAP-NodeJS/accessories
                  name: homekit-hostpath0
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/Lais/homekit/accessories
              name: homekit-hostpath0
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: mqttautodomo
      name: mqttautodomo
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: mqttautodomo
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: mqttautodomo
        spec:
          containers:
            - image: eclipse-mosquitto
              name: mqttautodomo
              ports:
                - containerPort: 1883
                - containerPort: 9001
              resources: {}
              volumeMounts:
                - mountPath: /mosquitto/config
                  name: mqttautodomo-hostpath0
                - mountPath: /mosquitto/data
                  name: mqttautodomo-hostpath1
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/Lais/mosquitto/config
              name: mqttautodomo-hostpath0
            - hostPath:
                path: /home/Lais/mosquitto/data
              name: mqttautodomo-hostpath1
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: nodediverso
      name: nodediverso
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: nodediverso
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: nodediverso
        spec:
          containers:
            - image: eltonssilva/nodediverso:armv7_1.0
              name: nodediverso
              ports:
                - containerPort: 8085
                - containerPort: 4555
              resources: {}
              volumeMounts:
                - mountPath: /home/node/app/configs
                  name: nodediverso-hostpath0
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/Lais/configs
              name: nodediverso-hostpath0
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: noderedautodomo
      name: noderedautodomo
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: noderedautodomo
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: noderedautodomo
        spec:
          containers:
            - image: raymondmm/node-red
              name: noderedautodomo
              ports:
                - containerPort: 1880
                - containerPort: 8082
                - containerPort: 8080
              resources: {}
              volumeMounts:
                - mountPath: /data
                  name: noderedautodomo-hostpath0
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/Lais/nodered/.node-red/data
              name: noderedautodomo-hostpath0
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: phpmyadmin
      name: phpmyadmin
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: phpmyadmin
      strategy: {}
      template:
        metadata:
          labels:
            io.kompose.service: phpmyadmin
        spec:
          containers:
            - image: sk278/phpmyadmin-armhf:4.8.3
              name: phpmyadmin
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: supervisorio
      name: supervisorio
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: supervisorio
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: supervisorio
        spec:
          containers:
            - image: eltonssilva/supervisorio:armv7_1.0
              name: supervisorio
              ports:
                - containerPort: 80
                - containerPort: 443
              resources: {}
              volumeMounts:
                - mountPath: /var/www/html/
                  name: supervisorio-hostpath0
                - mountPath: /home/pi/HAP-NodeJS/accessories/
                  name: supervisorio-hostpath1
                - mountPath: /home/node/app/configs
                  name: supervisorio-hostpath2
                - mountPath: /etc/ssl/localcerts/
                  name: supervisorio-hostpath3
                - mountPath: /etc/apache2/sites-available/
                  name: supervisorio-hostpath4
                - mountPath: /etc/apache2/sites-enabled/
                  name: supervisorio-hostpath5
                - mountPath: /etc/apache2/mods-enabled/ssl.conf
                  name: supervisorio-hostpath6
                - mountPath: /etc/apache2/mods-enabled/ssl.load
                  name: supervisorio-hostpath7
                - mountPath: /etc/apache2/mods-enabled/socache_shmcb.load
                  name: supervisorio-hostpath8
                - mountPath: /etc/mosquitto/config
                  name: supervisorio-hostpath9
                - mountPath: /etc/mosquitto/data
                  name: supervisorio-hostpath10
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/Lais/php/www
              name: supervisorio-hostpath0
            - hostPath:
                path: /home/Lais/homekit/accessories
              name: supervisorio-hostpath1
            - hostPath:
                path: /home/Lais/configs
              name: supervisorio-hostpath2
            - hostPath:
                path: /home/Lais/php/localcerts
              name: supervisorio-hostpath3
            - hostPath:
                path: /home/Lais/php/sites-available
              name: supervisorio-hostpath4
            - hostPath:
                path: /home/Lais/php/sites-enabled
              name: supervisorio-hostpath5
            - hostPath:
                path: /home/Lais/php/mods-enabled/ssl.conf
              name: supervisorio-hostpath6
            - hostPath:
                path: /home/Lais/php/mods-enabled/ssl.load
              name: supervisorio-hostpath7
            - hostPath:
                path: /home/Lais/php/mods-enabled/socache_shmcb.load
              name: supervisorio-hostpath8
            - hostPath:
                path: /home/Lais/mosquitto/config
              name: supervisorio-hostpath9
            - hostPath:
                path: /home/Lais/mosquitto/data
              name: supervisorio-hostpath10
    status: {}
  
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        io.kompose.service: zigbee2mqtt
      name: zigbee2mqtt
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: zigbee2mqtt
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            io.kompose.service: zigbee2mqtt
        spec:
          containers:
            - env:
                - name: TZ
                  value: Europe/Amsterdam
              image: koenkk/zigbee2mqtt:latest
              name: zigbee2mqtt
              resources: {}
              securityContext:
                privileged: true
              volumeMounts:
                - mountPath: /app/data
                  name: zigbee2mqtt-hostpath0
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /home/Lais/zigbee2mqtt/data
              name: zigbee2mqtt-hostpath0
    status: {}

kind: List

metadata: {}
